# Tasks

- create an empty repository on GitHub
([list of commits](https://github.com/bernardo-dauria/rshiny-case-study/commits/master))
- create a new Project of type _Version Control_ using the url of the GitHub repository 
**commit** and **push** &mdash; [**C&P**](https://github.com/bernardo-dauria/rshiny-case-study/commit/ce1c74d93f0af9d99b1cfae5929e40dbcb60bc97)
- crate a new file of type _Shiny Web App_ give the name _my_app_
- make a first **commit** and **push** &mdash; [**C&P**](https://github.com/bernardo-dauria/rshiny-case-study/commit/fe81d0f31f8002b86749787426906f11d3a65528)

<!--- -->
- load and show `gapminder` data by `tableOutput/renderTable`
&mdash; [**C&P**](https://github.com/bernardo-dauria/rshiny-case-study/commit/47592e3a5f24aed8e91828e6aa67e7a53cfe75be)

<!--- -->
- add the `<selector>` to filter on the year column
&mdash; [**C&P**](https://github.com/bernardo-dauria/rshiny-case-study/commit/b5a5595078d48e01fe2ee4665ce19129e15abcbf)

<!--- -->
- allow multiple selection using `%in%`
&mdash; [**C&P**](https://github.com/bernardo-dauria/rshiny-case-study/commit/e092f923f88577abed978a85f7cae66421ed2df8)

<!--- -->
- adding a panel showing a plot
&mdash; [**C&P**](https://github.com/bernardo-dauria/rshiny-case-study/commit/e3055475ec59ce28f0b1ea2f6dc6c535e1b59611)

<!--- -->
- use reactive elements
&mdash; [**C&P**](https://github.com/bernardo-dauria/rshiny-case-study/commit/ed9a020cd09ed639bbaa9fcc8fce2cc5b8768010)

<!--- -->
- plot multiple years
&mdash; [**C&P**](https://github.com/bernardo-dauria/rshiny-case-study/commit/72cbe190f1d71316c7a2c0650083ca3b255fcf2a)

<!--- -->
- plotting hover info
&mdash; [**C&P**](https://github.com/bernardo-dauria/rshiny-case-study/commit/b6b558eaa6fe9f558af9e837690e36ee187d6a63)

<!--- -->
- validate values
&mdash; [**C&P**](https://github.com/bernardo-dauria/rshiny-case-study/commit/aae3e82630fb3020218f343a53e4960d83bfd76c)

<!--- -->
- Plotly graph
&mdash; [**C&P**](https://github.com/bernardo-dauria/rshiny-case-study/commit/23e8dbc1c0ba63a6c28c4da906ce08d6eea6c32c)

<!--- -->
- use shinyjs
&mdash; [**C&P**](https://github.com/bernardo-dauria/rshiny-case-study/commit/2122cee73ad418ab1576572d48763f14660d0995)

<!--- -->
- complete map
&mdash; [**C&P**](https://github.com/bernardo-dauria/rshiny-case-study/commit/10d10514a979799961f1e960828e659d295bcb1f)

<!--- -->
- add download button
&mdash; [**C&P**](https://github.com/bernardo-dauria/rshiny-case-study/commit/c52c187b0cb33cdcce4f602f4ece3b2adbd77a5c)

<!--- -->
## References
 - [Shiny on RStudio](https://shiny.rstudio.com/)
 
 - [Shiny written tutorial](https://shiny.rstudio.com/tutorial/written-tutorial/lesson1/)
 
 - [Shiny embedded examples](https://shiny.rstudio.com/tutorial/written-tutorial/lesson1/#go-further)
 
 - [Shiny Function reference version 1.2.0](https://shiny.rstudio.com/reference/shiny/1.2.0/)
 
 - [Shiny HTML Tags Glossary](https://shiny.rstudio.com/articles/tag-glossary.html)
 
 - [Shiny Widget Gallery](https://shiny.rstudio.com/gallery/widget-gallery.html)
